FROM golang:alpine as builder

WORKDIR /code
COPY go.mod go.sum /code/
RUN go mod download

COPY . /code
RUN CGO_ENABLED=0 go build -trimpath -ldflags '-s -w -extldflags "-static"' -o boots ./cmd/boots/


FROM alpine
WORKDIR /
#USER boots

#COPY scripts/etc-passwd /etc/passwd
COPY --from=builder /code/boots /boots
ENTRYPOINT ["/boots"]
